### ISSUE TITLE
Versioned modified files are not highlighted in the project tree

### ISSUE THREAD

**Issue by gMatas** [pbidwell/HippoTheme#1]
Versioned files that were modified are not highlighted in any way in the project tree. Here's a comparison of the same file and change in IntelliJ's standard light theme and Hippo's:

IntelliJ Light theme:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/26392564/196635576-f75338f0-a66e-4fe7-9234-6913f37c21aa.png">

Hippo theme:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/26392564/196635645-c3b2596a-d0ac-4a3f-bb9e-f227da8ab128.png">

Other than that, I really like this theme, great job on it! I would love to use it as my main light theme if not for this issue.

---

Running on:
- PyCharm 2022.2.2 (Community Edition)
- Hippo Theme 1.2

**Comment by pbidwell** [comment]
Thanks for raising the issue - completely missed this. I should have some time this week to get this patched up.

**Comment by pbidwell** [comment]
@gMatas Sorry for the delay - I completely forgot to close this issue. The latest version of the plugin (1.5 as of this writing) has this fix.
